### ISSUE TITLE
producers outpace consumer thread

### ISSUE THREAD

**Issue by abrandoned** [mxenabled/active_publisher#21]
In the async publisher we have seen producers outpace the consumer thread (since there is only a single consumer thread and on our servers as many as 80 producer threads)

Maybe build out a mechanism for managing producer/consumer that fluctuates based on the amount to be consumed (just an idea): maybe something like a "maximum_single_consumer_threshold" that when it is hit causes multiple new consumer threads to be spawned until the queue shrinks back down

the async publisher is great, but running into edge cases like this can be hard to troubleshoot and I hope we can find solutions that are as passive as possible to use

**Comment by abrandoned** [comment]
@film42 @liveh2o @mmmries @quixoten

**Comment by film42** [comment]
@abrandoned if we're looking to optimize, I think keeping the connection open as long as we can would yield another performance boost. https://github.com/mxenabled/active_publisher/blob/d63389fec313e71a76a943b3eec6cb76faf60ba8/lib/active_publisher/async/in_memory_adapter.rb#L109

**Comment by mmmries** [comment]
What if we did a backpressure mechanism? The publisher would check the size of the queue (no thread-safety needed) and if it is over a maximum threshold it waits for the queue to get back to a small size.

We could also log whenever that happens to make it easier to debug.

**Comment by abrandoned** [comment]
@film42 I think that would be very good ... maybe a block syntax that allows a multi-publish inside the `publish` call ... we could then do batched publishes when the queue is over a certain size

@mmmries we have a backpressure mechanism currently (we drop publishes) ... are you saying that we should tune that to do something else? (like block the publish until queue size drops or timeout?)

**Comment by mmmries** [comment]
@abrandoned yep, I was thinking of blocking the publishing thread until the queue size goes down

**Comment by abrandoned** [comment]
@mmmries I think that's certainly an option, just hope we can find some other ways to minimize opportunities to block as well
